// Mocks generated by Mockito 5.4.6 from annotations
// in img_syncer/test/unit/mocks/remote_storage_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cross_file/cross_file.dart' as _i5;
import 'package:img_syncer/proto/img_syncer.pbgrpc.dart' as _i2;
import 'package:img_syncer/storage/storage.dart' as _i7;
import 'package:img_syncer/storage/storage_interface.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:photo_manager/photo_manager.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeImgSyncerClient_0 extends _i1.SmartFake
    implements _i2.ImgSyncerClient {
  _FakeImgSyncerClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteStorageClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteStorageClient extends _i1.Mock
    implements _i3.RemoteStorageClient {
  MockRemoteStorageClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ImgSyncerClient get cli => (super.noSuchMethod(
        Invocation.getter(#cli),
        returnValue: _FakeImgSyncerClient_0(
          this,
          Invocation.getter(#cli),
        ),
      ) as _i2.ImgSyncerClient);

  @override
  _i4.Future<void> uploadXFile(_i5.XFile? file) => (super.noSuchMethod(
        Invocation.method(
          #uploadXFile,
          [file],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> uploadAssetEntity(_i6.AssetEntity? asset) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadAssetEntity,
          [asset],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.RemoteImage>> listImages(
    String? date,
    int? offset,
    dynamic maxReturn,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #listImages,
          [
            date,
            offset,
            maxReturn,
          ],
        ),
        returnValue:
            _i4.Future<List<_i7.RemoteImage>>.value(<_i7.RemoteImage>[]),
      ) as _i4.Future<List<_i7.RemoteImage>>);
}
